[workspace]
members = [
    "networking",
    "domain",
    "runtime"
, "examples/client", "examples/domain-manager", "examples/data-node", "examples/reconstruction-node", "base", "examples/relay", "examples/test-concurrent"]
resolver = "2"

[workspace.package]
rust-version = "1.81.0"

[workspace.dependencies]
libp2p = { path = "../../rust-libp2p/libp2p" }
libp2p-stream = { path = "../../rust-libp2p/protocols/stream" }
libp2p-webrtc = { path = "../../rust-libp2p/transports/webrtc" }
libp2p-webrtc-websys = { path = "../../rust-libp2p/transports/webrtc-websys" }
futures = "0.3.30"
serde = "1.0.210"
serde_json = "1.0.128"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = "1.40.0"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.42"
serde-wasm-bindgen = "0.6.5"
gloo-timers = "0.3.0"
quick-protobuf = "0.8.1"
quick-protobuf-codec = "0.3.1"
console_error_panic_hook = "0.1.7"
networking = { path = "networking" }
runtime = { path = "runtime" }
domain = { path = "domain" }
base = { path = "base" }
asynchronous-codec = "0.7.0"
